### ISSUE TITLE
Marquee monitor not rotated 180 degrees.  Picture does not fill monitor either.

### ISSUE THREAD

**Issue by egorka123456** [rinalim/PieMarquee2#5]
The marquee monitor is not rotated 180 degrees.  Also, the picture does not fill the monitor- it is squeezed in the vertical driection.

**Comment by egorka123456** [comment]
Corrected to 

VIEWER = "/opt/retropie/configs/all/PieMarquee2/omxiv-marquee /tmp/marquee.txt -f -d 7 -o 180 -a fill -t 5 -T blend

and all is correct again.

**Comment by rinalim** [comment]
Thanks for your comment. It will be helpful to others

**Comment by awilley** [comment]
i'm also running into a marquee rotation issue. running rpi4b. 
i need to rotate right 90 deg. is this still the correct command for that?
and where do i place the following?
VIEWER = "/opt/retropie/configs/all/PieMarquee2/omxiv-marquee /tmp/marquee.txt -f -d 7 -o 180 -a fill -t 5 -T blend

**Comment by awilley** [comment]
ahh actually i just  figured it out!
that modification goes in this file:
sudo nano /opt/retropie/configs/all/PieMarquee2/PieMarquee2.py

and for 90 rotation i just changed 180 to 90. worked perfectly for me! hopefully helps others.
