### ISSUE TITLE
Copy video file "maintitle.mp4" 

### ISSUE THREAD

**Issue by Bboy486** [rinalim/PieMarquee2#8]
If you use:

"You can set the default marquee as video.
Copy video file "maintitle.mp4" to "/home/pi/PieMarquee2/marquee/system/" folder (optional)"

How do you prevent it from looping forever? The mp4 file just keeps looping.

**Comment by rinalim** [comment]
Just delete '--loop' option at the 150th line.

**Comment by Bboy486** [comment]
Thank you!
I did not see that in the readme. 

Second question related to videos. 

I have 40 different videos. Is there anyway that i can have them in the folder and have the script randonly pick of of them at boot?

**Comment by Bboy486** [comment]
@rinalim kindly follow-up.
